# Generated by Django 4.2.3 on 2023-08-26 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('utoronto_id', models.CharField(db_index=True, max_length=255)),
                ('discord_id', models.PositiveIntegerField()),
                ('gitlab_id', models.PositiveIntegerField()),
            ],
        ),
    ]
