# Generated by Django 4.1.4 on 2023-01-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('discord_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('discord_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(through='eyolfbot.Membership', to='eyolfbot.user')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyolfbot.role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyolfbot.user'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'role')},
        ),
    ]
