# Generated by Django 4.2.4 on 2023-08-26 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eyolfbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='discord_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='gitlab_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eyolfbot_connection', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
