# Generated by Django 4.0.3 on 2022-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
