# Generated by Django 4.0.3 on 2022-03-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_increase_title_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['offering', 'resource', 'number']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['offering', 'kind', 'number']},
        ),
        migrations.AlterField(
            model_name='link',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.offering'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('resource', 'number'), ('offering', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('offering', 'kind', 'number')},
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('offering__isnull', True), ('resource__isnull', False)), models.Q(('offering__isnull', False), ('resource__isnull', True)), _connector='OR'), name='mutually_exclusive_offering_or_resource'),
        ),
    ]
