# Generated by Django 4.0.3 on 2022-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_name_or_title_to_ordering'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', True)), fields=('offering', 'kind'), name='unique_offering_and_kind_with_null_number'),
        ),
    ]
